name: 'Default'

init:
  width: &width 0.96
  height: &height 1.8
  mass: 75
  animations: 'Resources/Animations/DanyaPers.yaml'

properties:
  description: null
  max_health: 100
  dodge: 0.1
  walk_speed: 1.5  # Скорость ходьбы сущности
  run_speed: 4  # Скорость бега сущности
  jump_speed: 4.5 # Скорость прыжка

hits:

  arming:
    hit_1:
      damage: 10
      reload_time: 1
      box:
        x: 0.5
        y: 1.0
        w: 0.5
        h: 0.5
      animation: 'arming_1'
      animation_hatting_phase: 0.3

  throwing:
    throw_1:
      damage: 20
      reload_time: 0.4
      item: 'TennisBall'

      position:
        - 1
        - 1

      throw_speed: 10
      throw_angle: 0.5235

      start_angle: 0
      angular_speed: 10

      animation: 'throw_1'
      animation_hatting_phase: 0.5

rects:
  idle_rect:
    - *width
    - *height
  walking_rect:
    - *width
    - *height
  running_rect:
    - *width
    - 1.72

  sitting_rect:
    - *width
    - 0.9
  squatting_rect:
    - *width
    - 0.9

  lying_rect:
    - *width
    - *height
  crawling_rect:
    - *width
    - *height

  soaring_rect:
    - *width
    - *height
  jumping_rect:
    - *width
    - *height
  flying_rect:
    - *width
    - *height
  landing_rect:
    - *width
    - *height